name: Deploy jdiscord-function

on:
  push:
    paths:
      - 'function/jdiscord-function/**'
  workflow_dispatch:

env:
  AZURE_FUNCTION_APP_NAME: ${{ secrets.AZURE_FUNCTION_APP_NAME }}
  AZURE_FUNCTIONAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

jobs:
  deploy-function:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: RCFromCLE/terraform-azurerm-jmusicbot
          path: function/jdiscord-function

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        with: 
          app-name: ${{ secrets.AZURE_FUNCTION_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          package: function/jdiscord-function
          
      - name: Deployment Result
        run: |
          if [ $? -eq 0 ]; then
            echo "SUCCESS: Azure Function deployment completed successfully."
          else
            echo "ERROR: Azure Function deployment failed."
            exit 1
          fi

      - name: Workflow Summary
        run: |
          echo "========================================"
          echo "Workflow Execution Summary:"
          echo "----------------------------------------"
          echo "1. Azure Function Deployment: Successful"
          echo "========================================"
          echo "JMusicBot has been successfully updated and deployed."
