name: Deploy JDiscordBot Function

on:
  push:
    paths:
      - 'function/**'
  workflow_dispatch:

env:
  AZURE_FUNCTION_APP_NAME: ${{ secrets.AZURE_FUNCTION_APP_NAME }}  # Azure Function App name
  NODE_VERSION: '16.x'                                              # Node.js version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
      with:
        repository: 'RCFromCLE/terraform-azurerm-jmusicbot'    # Specify the repository to checkout
        path: 'terraform-azurerm-jmusicbot'                    # Specify the path where the repository is checked out

    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: 'Resolve Project Dependencies Using Npm'
      shell: pwsh
      run: |
        pushd 'terraform-azurerm-jmusicbot/function'
        npm install
        npm run build --if-present
        npm run test --if-present
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ secrets.AZURE_FUNCTION_APP_NAME }}
        package: 'terraform-azurerm-jmusicbot/function'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
