name: Trigger Terraform and Deploy

on:
  repository_dispatch:
    types: [module-updated]
  workflow_dispatch:

env:
  TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
  TF_WORKSPACE_NAME: ${{ secrets.TF_WORKSPACE_NAME }}

jobs:
  trigger-and-monitor-terraform:
    runs-on: ubuntu-latest
    outputs:
      apply_success: ${{ steps.check_apply.outputs.success }}
    steps:
      - name: Get Workspace ID
        id: workspace
        run: |
          WORKSPACE_ID=$(curl \
            --header "Authorization: Bearer ${{ secrets.TF_API_TOKEN }}" \
            --header "Content-Type: application/vnd.api+json" \
            https://app.terraform.io/api/v2/organizations/${TF_CLOUD_ORGANIZATION}/workspaces/${TF_WORKSPACE_NAME} \
            | jq -r '.data.id')
          echo "::set-output name=id::$WORKSPACE_ID"

      - name: Trigger Terraform Apply
        id: trigger_apply
        run: |
          RESPONSE=$(curl \
            --header "Authorization: Bearer ${{ secrets.TF_API_TOKEN }}" \
            --header "Content-Type: application/vnd.api+json" \
            --request POST \
            --data '{"data": {"attributes": {"message": "Triggered by GitHub Actions - Update JMusicBot"}, "type":"runs", "relationships": {"workspace": {"data": {"type": "workspaces", "id": "${{ steps.workspace.outputs.id }}"}}}}}' \
            https://app.terraform.io/api/v2/runs)
          RUN_ID=$(echo $RESPONSE | jq -r '.data.id')
          echo "::set-output name=run_id::$RUN_ID"

      - name: Check Terraform Apply Status
        id: check_apply
        run: |
          while true; do
            STATUS=$(curl \
              --header "Authorization: Bearer ${{ secrets.TF_API_TOKEN }}" \
              --header "Content-Type: application/vnd.api+json" \
              https://app.terraform.io/api/v2/runs/${{ steps.trigger_apply.outputs.run_id }} \
              | jq -r '.data.attributes.status')
            
            if [ "$STATUS" = "applied" ]; then
              echo "::set-output name=success::true"
              break
            elif [ "$STATUS" = "errored" ] || [ "$STATUS" = "canceled" ] || [ "$STATUS" = "discarded" ]; then
              echo "::set-output name=success::false"
              break
            fi
            
            echo "Terraform apply still in progress. Current status: $STATUS"
            sleep 30
          done

  deploy-function:
    needs: trigger-and-monitor-terraform
    if: needs.trigger-and-monitor-terraform.outputs.apply_success == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        with: 
          app-name: ${{ secrets.AZURE_FUNCTION_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}