name: Check for JMusicBot Update and TF Apply

on:
  schedule:
    - cron: '30 9 * * *'  # Run daily at 5:30 AM EST - Will only run tf apply if new release is detected (scheduled run)
  workflow_dispatch:  # manual trigger, will run tf apply regardless of new release or not (manual run)

env:
  TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
  TF_WORKSPACE_NAME: ${{ secrets.TF_WORKSPACE_NAME }}
  AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
  AZURE_VM_NAME: ${{ secrets.AZURE_VM_NAME }}
  FUNCTION_APP_NAME: jdiscord-function
  MODULE_REPO: RCFromCLE/terraform-azurerm-jmusicbot

jobs:
  check-and-apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Check for updates
        id: check_updates
        run: |
          # Check module version
          module_latest_release=$(curl -s https://api.github.com/repos/${{ env.MODULE_REPO }}/releases/latest | jq -r .tag_name)
          echo "Latest module release: $module_latest_release"
          current_module_version=$(grep 'version = ' main.tf | sed 's/.*version = "\(.*\)".*/\1/')
          echo "Current module version: $current_module_version"
          
          # Check JMusicBot version
          jar_latest_release=$(curl -s https://api.github.com/repos/jagrosh/MusicBot/releases/latest | jq -r .tag_name)
          echo "Latest JMusicBot release: $jar_latest_release"
          current_jar_version=$(grep 'default.*JMusicBot-.*\.jar' variables.tf | sed 's/.*JMusicBot-\(.*\)\.jar.*/\1/')
          echo "Current JMusicBot version: $current_jar_version"
          
          # Compare versions
          if [ "$module_latest_release" != "$current_module_version" ] || [ "$jar_latest_release" != "$current_jar_version" ]; then
            echo "update_needed=true" >> $GITHUB_OUTPUT
            echo "module_latest_version=$module_latest_release" >> $GITHUB_OUTPUT
            echo "jar_latest_version=$jar_latest_release" >> $GITHUB_OUTPUT
            echo "Update needed. Proceeding with update."
          else
            echo "update_needed=false" >> $GITHUB_OUTPUT
            echo "No update needed."
          fi

      - name: Update main.tf
        if: steps.check_updates.outputs.update_needed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          sed -i 's/version = "[0-9.]*"/version = "${{ steps.check_updates.outputs.module_latest_version }}"/' main.tf
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add main.tf
          git commit -m "Update module version to ${{ steps.check_updates.outputs.module_latest_version }}" || echo "No changes to commit."
          git push https://RCFromCLE:${{ secrets.PAT_TOKEN }}@github.com/RCFromCLE/terraform-azurerm-jmusicbot-config.git || echo "No changes to push."

     - name: Update variables.tf
        if: steps.check_updates.outputs.update_needed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          new_jar_path="JMusicBot-${{ steps.check_updates.outputs.jar_latest_version }}.jar"
          sed -i 's/default\s*=\s*"JMusicBot-.*\.jar"/default = "'$new_jar_path'"/' variables.tf
          git add variables.tf
          git commit -m "Update jar_path in variables.tf to $new_jar_path" || echo "No changes to commit."
          git push https://RCFromCLE:${{ secrets.PAT_TOKEN }}@github.com/RCFromCLE/terraform-azurerm-jmusicbot-config.git || echo "No changes to push."

      - name: Exit if no update needed (scheduled run)
        if: steps.check_updates.outputs.update_needed == 'false' && github.event_name == 'schedule'
        run: |
          echo "No update needed. Exiting workflow."
          exit 0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Disable Function App
        run: |
          echo "Disabling Function App..."
          az functionapp stop --name ${{ env.FUNCTION_APP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }}

      - name: Check Initial VM Power State
        id: check_initial_state
        run: |
          echo "Checking initial VM power state..."
          VM_STATE=$(az vm get-instance-view \
            --resource-group "$AZURE_RESOURCE_GROUP" \
            --name "$AZURE_VM_NAME" \
            --query instanceView.statuses[1].displayStatus \
            -o tsv)
          echo "Initial VM Power State: $VM_STATE"
          echo "initial_state=$VM_STATE" >> $GITHUB_OUTPUT
          if [ "$VM_STATE" != "VM running" ]; then
            echo "Starting VM..."
            az vm start --resource-group "$AZURE_RESOURCE_GROUP" --name "$AZURE_VM_NAME"
            echo "Waiting for VM to be in running state..."
            TIMEOUT=600  # 10 minutes timeout
            start_time=$(date +%s)
            while [ "$VM_STATE" != "VM running" ]; do
              current_time=$(date +%s)
              if [ $((current_time - start_time)) -gt $TIMEOUT ]; then
                echo "Timeout waiting for VM to start. Exiting."
                exit 1
              fi
              sleep 30
              VM_STATE=$(az vm get-instance-view \
                --resource-group "$AZURE_RESOURCE_GROUP" \
                --name "$AZURE_VM_NAME" \
                --query instanceView.statuses[1].displayStatus \
                -o tsv)
              echo "Current VM state: $VM_STATE"
            done
            echo "VM is now running."
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Initialize Terraform
        run: terraform init

      - name: Get Workspace ID
        id: workspace
        run: |
          echo "Getting Terraform Cloud Workspace ID..."
          WORKSPACE_ID=$(curl \
            --header "Authorization: Bearer ${{ secrets.TF_API_TOKEN }}" \
            --header "Content-Type: application/vnd.api+json" \
            https://app.terraform.io/api/v2/organizations/${TF_CLOUD_ORGANIZATION}/workspaces/${TF_WORKSPACE_NAME} \
            | jq -r '.data.id')
          echo "Workspace ID: $WORKSPACE_ID"
          echo "id=$WORKSPACE_ID" >> $GITHUB_OUTPUT

      - name: Trigger Terraform Apply
        id: apply
        run: |
          echo "Triggering Terraform Apply..."
          RESPONSE=$(curl -s -w "\n%{http_code}" \
            --header "Authorization: Bearer ${{ secrets.TF_API_TOKEN }}" \
            --header "Content-Type: application/vnd.api+json" \
            --request POST \
            --data '{
              "data": {
                "type": "runs",
                "attributes": {
                  "is-destroy": false,
                  "message": "Update triggered - Module: ${{ steps.check_updates.outputs.module_latest_version }}, JMusicBot: ${{ steps.check_updates.outputs.jar_latest_version }}",
                  "auto-apply": true,
                  "refresh": true,
                  "replace-addrs": ["module.jmusicbot.azurerm_virtual_machine_extension.run_jdiscordbot"]
                },
                "relationships": {
                  "workspace": {
                    "data": {
                      "type": "workspaces",
                      "id": "${{ steps.workspace.outputs.id }}"
                    }
                  }
                }
              }
            }' \
            https://app.terraform.io/api/v2/runs)
          
          HTTP_STATUS=$(echo "$RESPONSE" | tail -n1)
          BODY=$(echo "$RESPONSE" | sed '$d')
          
          if [ "$HTTP_STATUS" -eq 201 ]; then
            echo "Terraform apply triggered successfully."
            RUN_ID=$(echo "$BODY" | jq -r '.data.id')
            echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
          else
            echo "Failed to trigger Terraform apply. HTTP status: $HTTP_STATUS"
            echo "Error message: $(echo "$BODY" | jq -r '.errors[0].title')"
            exit 1
          fi

      - name: Monitor Terraform Apply Status
        run: |
          echo "Monitoring Terraform Apply status..."
          while true; do
            STATUS=$(curl \
              --header "Authorization: Bearer ${{ secrets.TF_API_TOKEN }}" \
              --header "Content-Type: application/vnd.api+json" \
              https://app.terraform.io/api/v2/runs/${{ steps.apply.outputs.run_id }} \
              | jq -r '.data.attributes.status')
            
            echo "Current status: $STATUS"
            
            if [ "$STATUS" = "applied" ]; then
              echo "SUCCESS: Terraform apply completed successfully."
              break
            elif [ "$STATUS" = "errored" ] || [ "$STATUS" = "canceled" ] || [ "$STATUS" = "discarded" ]; then
              echo "ERROR: Terraform apply failed with status: $STATUS"
              exit 1
            fi
            
            sleep 30
          done
          
      - name: Restore Initial VM Power State
        if: steps.check_initial_state.outputs.initial_state != 'VM running'
        run: |
          echo "Restoring VM to initial power state (powering off)..."
          az vm deallocate --resource-group "$AZURE_RESOURCE_GROUP" --name "$AZURE_VM_NAME"
          echo "VM powered off."

      - name: Enable Function App
        run: |
          echo "Enabling Function App..."
          az functionapp start --name ${{ env.FUNCTION_APP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }}
