- name: Update module version in main.tf
        id: update-module
        run: |
          current_version=$(grep -oP 'source\s*=\s*"github.com/RCFromCLE/terraform-azurerm-jmusicbot\?ref=v\K[0-9.]+' main.tf)
          latest_version="${{ steps.check-release.outputs.new_version }}"
          
          echo "Current version: $current_version"
          echo "Latest version: $latest_version"
          
          if [ -z "$current_version" ]; then
            echo "Error: Could not find current version in main.tf"
            cat main.tf
            exit 1
          fi

          if [ -z "$latest_version" ]; then
            echo "Error: Could not fetch latest version"
            exit 1
          fi
         
          if [ "$latest_version" != "v$current_version" ] && [ "$latest_version" != "null" ]; then
            echo "New version available: $latest_version"
            # Update main.tf
            sed -i 's|\(source\s*=\s*"github.com/RCFromCLE/terraform-azurerm-jmusicbot?ref=v\)[0-9.]*|\1'"${latest_version#v}"'|' main.tf
            
            echo "Updated main.tf content:"
            cat main.tf
            
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add main.tf
            git commit -m "Update jmusicbot module version to $latest_version"
            
            # Fetch the latest changes
            git fetch origin main
            
            # Attempt to rebase
            if git rebase origin/main; then
              # If rebase is successful, force push the changes
              git push --force-with-lease
              echo "updated=true" >> $GITHUB_OUTPUT
              echo "new_version=$latest_version" >> $GITHUB_OUTPUT
            else
              # If rebase fails, undo the changes and exit
              git rebase --abort
              git reset --hard origin/main
              echo "Failed to update due to conflicts. Please check the repository manually."
              echo "updated=false" >> $GITHUB_OUTPUT
              exit 1
            fi
          else
            echo "No new version available or unable to fetch latest version. Current version is up to date."
            echo "updated=false" >> $GITHUB_OUTPUT
          fi
